### ISSUE TITLE
pino-roll Is it based on main thread or sub-thread?

### ISSUE THREAD

**Issue by jinxiaoman** [mcollina/pino-roll#57]
I just learned about him and it’s cool. Before, I created a sub-thread fs to write by myself. I would like to ask whether pino-roll is a sub-thread or the main thread. If it is the main thread, will there be any performance problems when writing a large number of logs?

**Comment by GuyAgiv** [comment]
pino-roll is a variant of transport.
Transports mechanism ran on a worker thread by its nature, so for your question, No it doesn't run on the main thread (and that's a good thing)
