### ISSUE TITLE
pino-roll with pino-pretty

### ISSUE THREAD

**Issue by GasparAdragna** [mcollina/pino-roll#81]
Hi! I'm trying to add log rotation to my project which currently uses pino-pretty.

I really like the idea of this lib and its really easy to set up.

The downside im finding is that i cannot use the pino-pretty which i quite like.

Is there a way to use both? Im getting the logs on my rotation files as default from pino.

Thanks

This is my code, the commented section is the settings i was using for file logging, but the file was getting out of hand.

```javascript
import pino from "pino";

const logger = pino({
  level: "debug",
  transport: {
    targets: [
      {
        level: "debug",
        options: {
          file: process.env.LOGGING_FILE,
          frequency: "daily",
          mkdir: true,
        },
        // options: {
        //   colorize: false,
        //   destination: process.env.LOGGING_FILE,
        //   mkdir: true,
        //   translateTime: "SYS:dd-mm-yyyy HH:mm:ss",
        // },
        // target: "pino-pretty",
        target: "pino-roll",
      },
      {
        level: "info",
        options: {
          colorize: true,
          destination: 1,
          translateTime: "SYS:dd-mm-yyyy HH:mm:ss",
        },
        target: "pino-pretty",
      },
    ],
  },
});

export default logger;
```

**Comment by mcollina** [comment]
A good solution when seeing logs is to do:

```sh
cat mylogfile | npx pino-pretty | less
```

It's generically better to store log files in newline delimited json because you can post-process them easily. You can even use `jq` to filter things.

**Comment by GasparAdragna** [comment]
I tested your code and it worked pefectly with the output generated by pino-roll.

Thak you!
